packages:
  - 'apps/*'

ignoredBuiltDependencies:
  - electron-winstaller

onlyBuiltDependencies:
  - electron
  - esbuild
  - lefthook

packageExtensions:
  'electron-vite@*':
    peerDependencies:
      electron: '*'
